rm -r source/
mkdir source
cp -r ../md/canal/ source/canal/
cp -r ../md/clamav/ source/clamav/
cp -r ../md/consul/ source/consul/
cp -r ../md/Css/ source/Css/
cp -r ../md/DevOps/ source/DevOps/
cp -r ../md/Docker/ source/Docker/
cp -r ../md/Elasticsearch/ source/Elasticsearch/
cp -r ../md/Git/ source/Git/
cp -r ../md/Go/ source/Go/
cp -r ../md/Graylog/ source/Graylog/
cp -r ../md/Hive/ source/Hive/
cp -r ../md/img/ source/img/
cp -r ../md/Java/ source/Java/
cp -r ../md/JavaScript/ source/JavaScript/
cp -r ../md/Jenkins/ source/Jenkins/
cp -r ../md/Jetbrains/ source/Jetbrains/
cp -r ../md/Kafka/ source/Kafka/
cp -r ../md/Kali/ source/Kali/
cp -r ../md/Kotlin/ source/Kotlin/
cp -r ../md/Kubernetes/ source/Kubernetes/
cp -r ../md/KVM/ source/KVM/
cp -r ../md/Linux/ source/Linux/
cp -r ../md/Mac/ source/Mac/
cp -r ../md/Mongodb/ source/Mongodb/
cp -r ../md/MyCat/ source/MyCat/
cp -r ../md/MySQL/ source/MySQL/
cp -r ../md/Nacos/ source/Nacos/
cp -r ../md/Neo4j/ source/Neo4j/
cp -r ../md/NetWork/ source/NetWork/
cp -r ../md/Nginx/ source/Nginx/
cp -r ../md/notes/ source/notes/
cp -r ../md/other/ source/other/
cp -r ../md/otter/ source/otter/
cp -r ../md/prometheus/ source/prometheus/
cp -r ../md/Python/ source/Python/
cp -r ../md/RabbitMQ/ source/RabbitMQ/
cp -r ../md/Redis/ source/Redis/
cp -r ../md/shell/ source/shell/
cp -r ../md/SpringBoot/ source/SpringBoot/
cp -r ../md/SpringSecurity/ source/SpringSecurity/
cp -r ../md/tfs/ source/tfs/
cp -r ../md/tomcat/ source/tomcat/
cp -r ../md/tools/ source/tools/
cp -r ../md/vagrant/ source/vagrant/
cp -r ../md/Vim/ source/Vim/
cp -r ../md/开发技巧/ source/开发技巧/
cp -r ../md/性能测试/ source/性能测试/
cp -r ../md/渗透实例/ source/渗透实例/
cp -r ../md/环境搭建/ source/环境搭建/
cp -r ../md/通用代码/ source/通用代码/
cp -r ../md/面试学习/ source/面试学习/
cp -r ../md/项目实践/ source/项目实践/
node autoSider.js